openapi: 3.0.0
info:
  title: Carrito de Compras API
  version: 1.0.0
  description: >
    Esta API proporciona la funcionalidad de un carrito de compras, incluyendo la posibilidad de agregar productos, actualizar cantidades, eliminar productos,
    ver el contenido del carrito y aplicar cupones de descuento. Además, incluye la gestión de descuentos por temporada y persistencia de datos.
paths:
  /cart:
    get:
      summary: Ver contenido del carrito
      description: Obtiene la lista de productos en el carrito junto con sus cantidades y precios.
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'
                example:
                  - productId: "123"
                    name: "Laptop"
                    quantity: 2
                    price: 500.00
                    subtotal: 1000.00
                  - productId: "456"
                    name: "Mouse"
                    quantity: 1
                    price: 20.00
                    subtotal: 20.00
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
    post:
      summary: Agregar producto al carrito
      description: Agrega un producto al carrito o actualiza su cantidad si ya existe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddProductRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request. No se ha continuado la petición debido a datos erróneos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /cart/{productId}:
    delete:
      summary: Eliminar producto del carrito
      description: Elimina un producto específico del carrito según su ID.
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID del producto a eliminar
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request. No se ha continuado la petición debido a datos erróneos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
    put:
      summary: Actualizar cantidad de un producto en el carrito
      description: Actualiza la cantidad de un producto en el carrito. Si la cantidad es 0, el producto será eliminado automáticamente.
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID del producto a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateQuantityRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request. No se ha continuado la petición debido a datos erróneos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /cart/total:
    get:
      summary: Ver total del carrito
      description: Obtiene el costo total del carrito, incluyendo subtotales y descuentos aplicados.
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: float
                example:
                  total: 1020.00
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /cart/apply-coupon:
    post:
      summary: Aplicar cupón de descuento
      description: Valida y aplica un cupón de descuento al carrito si es válido y no ha sido utilizado previamente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplyCouponRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request. No se ha continuado la petición debido a datos erróneos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /cart/discounts:
    get:
      summary: Ver descuentos activos
      description: Obtiene una lista de los descuentos actuales aplicables a los productos del carrito.
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Discount'
                example:
                  - productId: "123"
                    discountPercentage: 5.0
                    startDate: "2023-01-01T00:00:00Z"
                    endDate: "2023-06-30T23:59:59Z"
                  - productId: "456"
                    discountPercentage: 15.0
                    startDate: "2023-07-01T00:00:00Z"
                    endDate: "2023-12-31T23:59:59Z"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
components:
  schemas:
    CartItem:
      type: object
      properties:
        productId:
          type: string
          description: ID único del producto
        name:
          type: string
          description: Nombre del producto
        quantity:
          type: integer
          description: Cantidad del producto en el carrito
        price:
          type: number
          format: float
          description: Precio unitario del producto
        subtotal:
          type: number
          format: float
          description: Subtotal calculado para este producto
    AddProductRequest:
      type: object
      properties:
        productId:
          type: string
          description: ID del producto a agregar
        quantity:
          type: integer
          description: Cantidad del producto a agregar
    UpdateQuantityRequest:
      type: object
      properties:
        quantity:
          type: integer
          description: Nueva cantidad del producto. Si es 0, el producto será eliminado.
    ApplyCouponRequest:
      type: object
      properties:
        couponCode:
          type: string
          description: Código del cupón a aplicar
    Discount:
      type: object
      properties:
        productId:
          type: string
          description: ID del producto al que se aplica el descuento
        discountPercentage:
          type: number
          format: float
          description: Porcentaje de descuento aplicado
        startDate:
          type: string
          format: date-time
          description: Fecha de inicio del descuento
        endDate:
          type: string
          format: date-time
          description: Fecha de finalización del descuento
    SuccessResponse:
      type: object
      properties:
        code :
          type: number
          description: codigo HTTP
        message:
          type: string
          description: Mensaje de éxito
        
      example:
        code : 200
        message: "Operación realizada con éxito"
        
    ErrorResponse400:
      type: object
      properties:
        code :
          type: number
          description: codigo HTTP
        error:
          type: string
          description: Descripción del error
        
      example:
        code : 400
        error: "Solicitud Incorrecta"  
          
    ErrorResponse500:
      type: object
      properties:
        code :
          type: number
          description: codigo HTTP
        error:
          type: string
          description: Descripción del error
        
      example:
        code : 500
        error: "Error interno del servidor"
        
